Add option to avoid auto-recovery when criu restore fails
Add option CRIU_RESTORE_DISABLE_RECOVERY that when not set to
a value then the server script will attempt to recover from
a failed restore with a normal server launch.

Note that this currently only handles when criu itself fails
to restore the process.  Additional work is needed to handle
when the JVM or Liberty restore hooks fail.

diff --git a/dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server b/dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
--- a/dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
+++ b/dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
@@ -39,6 +39,13 @@
 #                     appended to the end of the list of arguments and can therefore
 #                     override existing arguments, if desired.
 #
+# CRIU_RESTORE_DISABLE_RECOVERY - 
+#              When restoring a server from a checkpoint it is possible
+#              that CRIU will fail to restore the proces.  By default
+#              any failure to restore will result in the server
+#              recovering without using the checkpoint image.
+#              To disable this behavior set this to any value.
+#
 # PID_DIR    - The directory that should be used for server pid file(s).
 #              The default value is ${WLP_OUTPUT_DIR}/.pid
 #
@@ -1473,10 +1480,16 @@ case "$ACTION" in
     fi
 
     serverWorkingDirectory
-                  
-    if restoreServer false "$@" 
-    then
+
+    restoreServer false "$@"
+    rc=$?
+    if [ $rc = 0 ]; then
       exit 0
+    elif [ $rc -ne 1 ]; then
+      if [ -n "${CRIU_RESTORE_DISABLE_RECOVERY}" ]; then
+        exit $rc
+      fi
+      # will try to recover with a normal launch below
     fi
 
     if checkServer true
@@ -1549,9 +1562,15 @@ case "$ACTION" in
       "1" )
         serverWorkingDirectory
 
-        if restoreServer true "$@"
-        then
+        restoreServer true "$@"
+        rc=$?
+        if [ $rc = 0 ]; then
           exit 0
+        elif [ $rc -ne 1 ]; then
+          if [ -n "${CRIU_RESTORE_DISABLE_RECOVERY}" ]; then
+            exit $rc
+          fi
+          # will try to recover with a normal launch below
         fi
 
         mkdirs "${X_LOG_DIR}"
